/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryapp;

import com.sun.glass.events.KeyEvent;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import libraryapp.dao.BookDAO;
import libraryapp.pojo.BookPojo;

/**
 *
 * @author Ayush's HP
 */
public class AddBook extends javax.swing.JFrame {

    /**
     * Creates new form AddBook
     */
    public AddBook() {
        initComponents();
        this.setLocationRelativeTo(null);
        Toolkit t = Toolkit.getDefaultToolkit();
        Image img;
        img = t.getImage("src\\libraryapp\\appicons\\appSoftware_icon1.png");
        setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabelBookName = new javax.swing.JLabel();
        jLabelBookName1 = new javax.swing.JLabel();
        jLabelBookName2 = new javax.swing.JLabel();
        jLabelBookName3 = new javax.swing.JLabel();
        jLabelBookName4 = new javax.swing.JLabel();
        jLabelBookName5 = new javax.swing.JLabel();
        jTextFieldBName = new javax.swing.JTextField();
        jTextFieldBAuthor = new javax.swing.JTextField();
        jTextFieldBCost = new javax.swing.JTextField();
        jTextFieldBCode = new javax.swing.JTextField();
        jTextFieldBPublisher = new javax.swing.JTextField();
        jComboBoxBCategory = new javax.swing.JComboBox<>();
        jLabelBookName6 = new javax.swing.JLabel();
        jTextFieldBCount = new javax.swing.JTextField();
        jLabelBookSearch = new javax.swing.JLabel();
        jButtonAddBook = new javax.swing.JButton();
        jButtonClearAll = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldHidden = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Book");

        jPanel1.setBackground(new java.awt.Color(225, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabelBookName.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelBookName.setText("Category:");

        jLabelBookName1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelBookName1.setText("Book Title:");

        jLabelBookName2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelBookName2.setText("Author:");

        jLabelBookName3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelBookName3.setText("Cost (Rs):");

        jLabelBookName4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelBookName4.setText("Publisher:");

        jLabelBookName5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelBookName5.setText("Book Code:");

        jTextFieldBName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldBName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldBName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBNameFocusLost(evt);
            }
        });

        jTextFieldBAuthor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldBAuthor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldBAuthor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBAuthorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBAuthorFocusLost(evt);
            }
        });

        jTextFieldBCost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldBCost.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldBCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldBCost.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBCostFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBCostFocusLost(evt);
            }
        });
        jTextFieldBCost.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBCostKeyTyped(evt);
            }
        });

        jTextFieldBCode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldBCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldBCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBCodeFocusLost(evt);
            }
        });
        jTextFieldBCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBCodeKeyTyped(evt);
            }
        });

        jTextFieldBPublisher.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldBPublisher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldBPublisher.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBPublisherFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBPublisherFocusLost(evt);
            }
        });

        jComboBoxBCategory.setBackground(new java.awt.Color(0, 198, 174));
        jComboBoxBCategory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxBCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Architecture Engineering", "Automobile Engineering", "Civil Engineering", "Chemical Engineering", "Computer Science & Engineering", "Electronics & Communication Engineering", "Electrical Engineering", "Electronics & Instrumentation Engineering", "Food Technology Engineering", "Information Technology", "Industrial Production Engineering", "Mechanical Engineering" }));

        jLabelBookName6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelBookName6.setText("Book Count:");

        jTextFieldBCount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldBCount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldBCount.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldBCountFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldBCountFocusLost(evt);
            }
        });
        jTextFieldBCount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldBCountKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBookName1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookName4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookName3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookName2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookName, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookName5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextFieldBCost, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelBookName6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBCount, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                    .addComponent(jComboBoxBCategory, 0, 1, Short.MAX_VALUE)
                    .addComponent(jTextFieldBAuthor, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldBName)
                    .addComponent(jTextFieldBCode)
                    .addComponent(jTextFieldBPublisher, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBName, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxBCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(jLabelBookName2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBookName3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBCost, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookName6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBCount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBookName4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBPublisher, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBookName5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBCode, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelBookSearch.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        jLabelBookSearch.setText("Add New Book");

        jButtonAddBook.setBackground(new java.awt.Color(0, 198, 174));
        jButtonAddBook.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonAddBook.setText("Add Book");
        jButtonAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBookActionPerformed(evt);
            }
        });

        jButtonClearAll.setBackground(new java.awt.Color(0, 198, 174));
        jButtonClearAll.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonClearAll.setText("Clear All");
        jButtonClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearAllActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryapp/appicons/book-3.png"))); // NOI18N

        jTextFieldHidden.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButtonAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldHidden, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelBookSearch)
                        .addGap(97, 97, 97))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextFieldHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelBookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClearAll, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBCostKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBCostKeyTyped
        char c;
        c = evt.getKeyChar();
        String cost;
        cost = jTextFieldBCost.getText();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldBCostKeyTyped

    private void jTextFieldBCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBCodeKeyTyped
        char c;
        c = evt.getKeyChar();
        String code;
        code = jTextFieldBCode.getText();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldBCodeKeyTyped

    private void jButtonAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBookActionPerformed
        if (jTextFieldBName.getText().trim().isEmpty() || jTextFieldBAuthor.getText().trim().isEmpty() || jTextFieldBCost.getText().trim().isEmpty() || jTextFieldBPublisher.getText().trim().isEmpty() || jTextFieldBCode.getText().trim().isEmpty() || jTextFieldBCount.getText().trim().isEmpty()) {
            jTextFieldBName.requestFocus();
            jTextFieldBAuthor.requestFocus();
            jTextFieldBCost.requestFocus();
            jTextFieldBPublisher.requestFocus();
            jTextFieldBCode.requestFocus();
            jTextFieldBCount.requestFocus();
            jTextFieldHidden.requestFocus();
            String str;
            str = "Empty Fields !!";
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, str, "ACCESS DENIED !!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String bname = jTextFieldBName.getText().trim();
        String bauthor = jTextFieldBAuthor.getText().trim();
        int bcost = Integer.parseInt(jTextFieldBCost.getText().trim());
        int bcount = Integer.parseInt(jTextFieldBCount.getText().trim());
        String bcategory = jComboBoxBCategory.getItemAt(jComboBoxBCategory.getSelectedIndex());
        int bcode = Integer.parseInt(jTextFieldBCode.getText().trim());
        String bpublisher = jTextFieldBPublisher.getText().trim();
        try {
            int max = bcode + bcount;
            while (bcode < max) {
                BookPojo bookDetails = new BookPojo(bname, bauthor, bcost, bcategory, bpublisher, bcode);
                if (BookDAO.addBook(bookDetails)) {
                    bcode++;
                }
            }
            Dashboard d = new Dashboard();
            d.setLables();
            JOptionPane.showMessageDialog(null, "Books Saved Successfully !", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldBName.setText("");
            jTextFieldBAuthor.setText("");
            jTextFieldBCost.setText("");
            jTextFieldBCount.setText("");
            jTextFieldBPublisher.setText("");
            jTextFieldBCode.setText("");
        }
        catch (SQLException ex) {
            if (ex.getErrorCode() == 1) {
                JOptionPane.showMessageDialog(null, "Book Code Already Allotted !!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            else {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonAddBookActionPerformed

    private void jTextFieldBNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBNameFocusGained
        jTextFieldBName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jTextFieldBNameFocusGained

    private void jTextFieldBNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBNameFocusLost
        if (jTextFieldBName.getText().trim().isEmpty()) {
            jTextFieldBName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
    }//GEN-LAST:event_jTextFieldBNameFocusLost

    private void jTextFieldBAuthorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBAuthorFocusGained
        jTextFieldBAuthor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jTextFieldBAuthorFocusGained

    private void jTextFieldBAuthorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBAuthorFocusLost
        if (jTextFieldBAuthor.getText().trim().isEmpty()) {
            jTextFieldBAuthor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
    }//GEN-LAST:event_jTextFieldBAuthorFocusLost

    private void jTextFieldBCostFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBCostFocusGained
        jTextFieldBCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jTextFieldBCostFocusGained

    private void jTextFieldBCostFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBCostFocusLost
        if (jTextFieldBCost.getText().trim().isEmpty()) {
            jTextFieldBCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
    }//GEN-LAST:event_jTextFieldBCostFocusLost

    private void jTextFieldBPublisherFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBPublisherFocusGained
        jTextFieldBPublisher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jTextFieldBPublisherFocusGained

    private void jTextFieldBPublisherFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBPublisherFocusLost
        if (jTextFieldBPublisher.getText().trim().isEmpty()) {
            jTextFieldBPublisher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
    }//GEN-LAST:event_jTextFieldBPublisherFocusLost

    private void jTextFieldBCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBCodeFocusGained
        jTextFieldBCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jTextFieldBCodeFocusGained

    private void jTextFieldBCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBCodeFocusLost
        if (jTextFieldBCode.getText().trim().isEmpty()) {
            jTextFieldBCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
    }//GEN-LAST:event_jTextFieldBCodeFocusLost

    private void jButtonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearAllActionPerformed
        jTextFieldBName.setText("");
        jTextFieldBName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldBAuthor.setText("");
        jTextFieldBAuthor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldBCost.setText("");
        jTextFieldBCost.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldBPublisher.setText("");
        jTextFieldBPublisher.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldBCode.setText("");
        jTextFieldBCode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldBCount.setText("");
        jTextFieldBCount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jButtonClearAllActionPerformed

    private void jTextFieldBCountFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBCountFocusGained
        jTextFieldBCount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jTextFieldBCountFocusGained

    private void jTextFieldBCountFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldBCountFocusLost
        if (jTextFieldBCount.getText().trim().isEmpty()) {
            jTextFieldBCount.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
    }//GEN-LAST:event_jTextFieldBCountFocusLost

    private void jTextFieldBCountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBCountKeyTyped
        char c;
        c = evt.getKeyChar();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldBCountKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AddBook().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddBook;
    private javax.swing.JButton jButtonClearAll;
    private javax.swing.JComboBox<String> jComboBoxBCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBookName;
    private javax.swing.JLabel jLabelBookName1;
    private javax.swing.JLabel jLabelBookName2;
    private javax.swing.JLabel jLabelBookName3;
    private javax.swing.JLabel jLabelBookName4;
    private javax.swing.JLabel jLabelBookName5;
    private javax.swing.JLabel jLabelBookName6;
    private javax.swing.JLabel jLabelBookSearch;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldBAuthor;
    private javax.swing.JTextField jTextFieldBCode;
    private javax.swing.JTextField jTextFieldBCost;
    private javax.swing.JTextField jTextFieldBCount;
    private javax.swing.JTextField jTextFieldBName;
    private javax.swing.JTextField jTextFieldBPublisher;
    private javax.swing.JTextField jTextFieldHidden;
    // End of variables declaration//GEN-END:variables
}
