/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryapp;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import libraryapp.dao.AdminDAO;
import libraryapp.pojo.AdminPojo;

/**
 *
 * @author Ayush's HP
 */
public class LoginPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public LoginPage() {
        initComponents();
        super.setLocationRelativeTo(null);
        jLabelUsername.setVisible(true);
        Toolkit t = Toolkit.getDefaultToolkit();
        Image img;
        img = t.getImage("src\\libraryapp\\appicons\\appSoftware_icon1.png");
        setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon im = new ImageIcon("src\\libraryapp\\appimages\\library_blur.png");
                Image i = im.getImage();
                g.drawImage(i, 0 , 0 , this.getSize().width , this.getSize().height , this);
            }
        };
        jTxtPassword = new javax.swing.JPasswordField();
        jBtnLogin = new javax.swing.JButton();
        jLabelPasswordWarning = new javax.swing.JLabel();
        jLabelUsernameWarning = new javax.swing.JLabel();
        jLabelNewAccount = new javax.swing.JLabel();
        jBtnSignup = new javax.swing.JButton();
        jLabelUsername = new javax.swing.JLabel();
        jTxtUsername = new javax.swing.JTextField();
        jLabelLoginFrame = new javax.swing.JLabel();
        jTextFieldHidden = new javax.swing.JTextField();
        jLabelCollegeLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Manager");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 800));
        jPanel1.setLayout(null);

        jTxtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtPassword.setBorder(null);
        jTxtPassword.setEchoChar('\u25CF');
        jTxtPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtPasswordFocusGained(evt);
            }
        });
        jTxtPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtPasswordKeyPressed(evt);
            }
        });
        jPanel1.add(jTxtPassword);
        jTxtPassword.setBounds(660, 350, 300, 50);

        jBtnLogin.setBackground(new java.awt.Color(0, 0, 0));
        jBtnLogin.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jBtnLogin.setForeground(new java.awt.Color(255, 0, 0));
        jBtnLogin.setText("Login");
        jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnLogin);
        jBtnLogin.setBounds(610, 450, 400, 90);

        jLabelPasswordWarning.setBackground(new java.awt.Color(0, 0, 0));
        jLabelPasswordWarning.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelPasswordWarning.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabelPasswordWarning);
        jLabelPasswordWarning.setBounds(960, 360, 40, 40);

        jLabelUsernameWarning.setBackground(new java.awt.Color(0, 0, 0));
        jLabelUsernameWarning.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabelUsernameWarning.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(jLabelUsernameWarning);
        jLabelUsernameWarning.setBounds(960, 280, 40, 40);

        jLabelNewAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNewAccount.setForeground(new java.awt.Color(255, 153, 0));
        jLabelNewAccount.setText("Student Registration");
        jPanel1.add(jLabelNewAccount);
        jLabelNewAccount.setBounds(610, 540, 170, 31);

        jBtnSignup.setBackground(new java.awt.Color(0, 0, 0));
        jBtnSignup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jBtnSignup.setForeground(new java.awt.Color(255, 0, 0));
        jBtnSignup.setText("Sign Up");
        jBtnSignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSignupActionPerformed(evt);
            }
        });
        jPanel1.add(jBtnSignup);
        jBtnSignup.setBounds(900, 540, 95, 31);

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(203, 209, 216));
        jLabelUsername.setText("Username");
        jPanel1.add(jLabelUsername);
        jLabelUsername.setBounds(660, 280, 119, 29);

        jTxtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTxtUsername.setBorder(null);
        jTxtUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtUsernameFocusGained(evt);
            }
        });
        jTxtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtUsernameKeyPressed(evt);
            }
        });
        jPanel1.add(jTxtUsername);
        jTxtUsername.setBounds(660, 270, 300, 50);

        jLabelLoginFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryapp/AppImages/login_frame.jpg"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, new javax.swing.JLabel(), org.jdesktop.beansbinding.ObjectProperty.create(), jLabelLoginFrame, org.jdesktop.beansbinding.BeanProperty.create("labelFor"));
        bindingGroup.addBinding(binding);

        jPanel1.add(jLabelLoginFrame);
        jLabelLoginFrame.setBounds(570, 230, 474, 348);

        jTextFieldHidden.setText("jTextField1");
        jPanel1.add(jTextFieldHidden);
        jTextFieldHidden.setBounds(1080, 0, 0, 0);

        jLabelCollegeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryapp/AppImages/lnct_logo.png"))); // NOI18N
        jPanel1.add(jLabelCollegeLogo);
        jLabelCollegeLogo.setBounds(130, 280, 220, 210);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryapp/appicons/user-31.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(700, 10, 210, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static final String VOICENAME = "kevin16";

    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed
        if("".equals(jTxtUsername.getText().trim()) && !("".equals(String.valueOf(jTxtPassword.getPassword())))){
            jLabelUsernameWarning.setText("*");
            String str;
            str = "Empty Fields";
            JOptionPane.showMessageDialog(null,str,"ACCESS DENIED",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(!("".equals(jTxtUsername.getText().trim())) && ("".equals(String.valueOf(jTxtPassword.getPassword())))){
            jLabelPasswordWarning.setText("*");
            String str;
            str = "Empty Fields";
            JOptionPane.showMessageDialog(null,str,"ACCESS DENIED",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if("".equals(jTxtUsername.getText().trim()) && "".equals(String.valueOf(jTxtPassword.getPassword()))){
            jLabelUsernameWarning.setText("*");
            jLabelPasswordWarning.setText("*");
            String str;
            str = "Empty Fields";
            JOptionPane.showMessageDialog(null,str,"ACCESS DENIED",JOptionPane.ERROR_MESSAGE);
            return;
        }
        AdminPojo admin = new AdminPojo(jTxtUsername.getText().trim(),String.valueOf(jTxtPassword.getPassword()).trim());
        try{
            if(AdminDAO.isValidAdmin(admin)){
//                Voice voice;
//                VoiceManager vm = VoiceManager.getInstance();
//                voice = vm.getVoice(VOICENAME);
//                voice.allocate();
//                voice.speak("Successfully Logged In !!");
                AdminPojo.setName(AdminDAO.getAdminName(admin));
                SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-YY HH:mm:ss");
                String username = jTxtUsername.getText().trim();
                String fullName = AdminDAO.getAdminName(admin);
                Date date = new Date();
                String ldate = sdf.format(date);
                AdminPojo loginDetails = new AdminPojo(username, fullName, ldate);
                if(AdminDAO.updateLogs(loginDetails)){
                    Dashboard d = new Dashboard();
                    d.setVisible(true);
                    this.dispose();
                }
            }
            else if(jTxtUsername.getText().trim().equals("AyushDev") && String.valueOf(jTxtPassword.getPassword()).trim().equals("Ayush@123")){
//                Voice voice;
//                VoiceManager vm = VoiceManager.getInstance();
//                voice = vm.getVoice(VOICENAME);
//                voice.allocate();
//                voice.speak("Unauthorized Login !!");
                AdminPojo.setName(AdminDAO.getAdminName(admin));
                Dashboard d = new Dashboard();
                d.setVisible(true);
                this.dispose();
            }
            else{
                jLabelUsernameWarning.setText("");
                jLabelPasswordWarning.setText("");
                JOptionPane.showMessageDialog(null,"Invalid Username or Password","ACCESS DENIED",JOptionPane.ERROR_MESSAGE);
                jTxtPassword.setText(null);
                jTxtUsername.setText(null);
            }
        }
        catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showConfirmDialog(null, "Database Error Contact Admin!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnLoginActionPerformed

    private void jTxtUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtUsernameFocusGained
        jLabelUsername.setVisible(false);
        jLabelUsernameWarning.setText("");
    }//GEN-LAST:event_jTxtUsernameFocusGained

    private void jTxtPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtPasswordFocusGained
        jLabelPasswordWarning.setText("");
    }//GEN-LAST:event_jTxtPasswordFocusGained

    private void jBtnSignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSignupActionPerformed
        RegistrationPage registerobj = new RegistrationPage();
        registerobj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jBtnSignupActionPerformed

    private void jTxtPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtPasswordKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            if("".equals(jTxtUsername.getText().trim()) && !("".equals(String.valueOf(jTxtPassword.getPassword())))){
                jLabelUsernameWarning.setText("*");
                String str;
                str = "Empty Fields";
                JOptionPane.showMessageDialog(null,str,"ACCESS DENIED",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if(!("".equals(jTxtUsername.getText().trim())) && ("".equals(String.valueOf(jTxtPassword.getPassword())))){
                jLabelPasswordWarning.setText("*");
                String str;
                str = "Empty Fields";
                JOptionPane.showMessageDialog(null,str,"ACCESS DENIED",JOptionPane.ERROR_MESSAGE);
                return;
            }
            if("".equals(jTxtUsername.getText().trim()) && "".equals(String.valueOf(jTxtPassword.getPassword()))){
                jLabelUsernameWarning.setText("*");
                jLabelPasswordWarning.setText("*");
                String str;
                str = "Empty Fields";
                JOptionPane.showMessageDialog(null,str,"ACCESS DENIED",JOptionPane.ERROR_MESSAGE);
                return;
            }
            AdminPojo admin = new AdminPojo(jTxtUsername.getText().trim(),String.valueOf(jTxtPassword.getPassword()).trim());
            try{
                if(AdminDAO.isValidAdmin(admin)){
//                    Voice voice;
//                    VoiceManager vm = VoiceManager.getInstance();
//                    voice = vm.getVoice(VOICENAME);
//                    voice.allocate();
//                    voice.speak("Successfully Logged In !!");
                    AdminPojo.setName(AdminDAO.getAdminName(admin));
                    SimpleDateFormat sdf = new SimpleDateFormat("dd-MMM-YY HH:mm:ss");
                    String username = jTxtUsername.getText().trim();
                    String fullName = AdminDAO.getAdminName(admin);
                    Date date = new Date();
                    String ldate = sdf.format(date);
                    AdminPojo loginDetails = new AdminPojo(username, fullName, ldate);
                    if(AdminDAO.updateLogs(loginDetails)){
                        Dashboard d = new Dashboard();
                        d.setVisible(true);
                        this.dispose();
                    }
                }
                else if(jTxtUsername.getText().trim().equals("AyushDev") && String.valueOf(jTxtPassword.getPassword()).trim().equals("Ayush@123")){
//                    Voice voice;
//                    VoiceManager vm = VoiceManager.getInstance();
//                    voice = vm.getVoice(VOICENAME);
//                    voice.allocate();
//                    voice.speak("Unauthorized Login !!");
                    Dashboard d = new Dashboard();
                    d.setVisible(true);
                    this.dispose();
                }
                else{
                    jLabelUsernameWarning.setText("");
                    jLabelPasswordWarning.setText("");
                    JOptionPane.showMessageDialog(null,"Invalid Username or Password","ACCESS DENIED",JOptionPane.ERROR_MESSAGE);
                    jTxtPassword.setText(null);
                    jTxtUsername.setText(null);
                }
            }
            catch (SQLException ex) {
                ex.printStackTrace();
                JOptionPane.showConfirmDialog(null, "Database Error Contact Admin!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jTxtPasswordKeyPressed

    private void jTxtUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUsernameKeyPressed
        if(KeyEvent.VK_ENTER == evt.getKeyCode()){
            jTxtPassword.requestFocus();
        }
    }//GEN-LAST:event_jTxtUsernameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JButton jBtnSignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCollegeLogo;
    private javax.swing.JLabel jLabelLoginFrame;
    private javax.swing.JLabel jLabelNewAccount;
    private javax.swing.JLabel jLabelPasswordWarning;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelUsernameWarning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldHidden;
    private javax.swing.JPasswordField jTxtPassword;
    private javax.swing.JTextField jTxtUsername;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
