/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package libraryapp;

import static libraryapp.dao.StudentDAO.*;
import libraryapp.pojo.StudentPojo;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Ayush's HP
 */
public class RegistrationPage extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationPage
     */
    public RegistrationPage() {
        initComponents();
        jLabelGenderWarning.setVisible(false);
        super.setLocationRelativeTo(null);
        Toolkit t = Toolkit.getDefaultToolkit();
        Image img;
        img = t.getImage("src\\libraryapp\\appicons\\appSoftware_icon1.png");
        setIconImage(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnGroupGender = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel(){
            public void paintComponent(Graphics g){
                ImageIcon im = new ImageIcon("src\\libraryapp\\appimages\\library_blur.png");
                Image i = im.getImage();
                g.drawImage(i, 0 , 0 , this.getSize().width , this.getSize().height , this);
            }
        };
        jTextFieldFirstName = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jButtonRegister = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldAccsoftID = new javax.swing.JTextField();
        jTextFieldPhoneNo = new javax.swing.JTextField();
        jComboBoxInstitution = new javax.swing.JComboBox<>();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelAccsoftID = new javax.swing.JLabel();
        jLabelCollege = new javax.swing.JLabel();
        jLabelSemester = new javax.swing.JLabel();
        jLabelSection = new javax.swing.JLabel();
        jLabelEmailEx = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelGenderWarning = new javax.swing.JLabel();
        jLabelPhone = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelBranch = new javax.swing.JLabel();
        jComboBoxBranch = new javax.swing.JComboBox<>();
        jComboBoxSection = new javax.swing.JComboBox<>();
        jComboBoxSemester = new javax.swing.JComboBox<>();
        jLabelHaveAccount = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabelCollegeLogo = new javax.swing.JLabel();
        jLabelRegistration = new javax.swing.JLabel();
        jTextFieldHidden = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Library Manager");

        jPanel2.setPreferredSize(new java.awt.Dimension(1080, 801));
        jPanel2.setLayout(null);

        jTextFieldFirstName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldFirstName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldFirstNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldFirstNameFocusLost(evt);
            }
        });
        jTextFieldFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFirstNameKeyPressed(evt);
            }
        });
        jPanel2.add(jTextFieldFirstName);
        jTextFieldFirstName.setBounds(600, 110, 200, 50);

        jButtonLogin.setBackground(new java.awt.Color(0, 0, 0));
        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(255, 0, 0));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonLogin);
        jButtonLogin.setBounds(940, 730, 90, 30);

        jButtonRegister.setBackground(new java.awt.Color(0, 0, 0));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(255, 0, 0));
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonRegister);
        jButtonRegister.setBounds(879, 675, 150, 50);

        jButtonReset.setBackground(new java.awt.Color(0, 0, 0));
        jButtonReset.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonReset.setForeground(new java.awt.Color(255, 0, 0));
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonReset);
        jButtonReset.setBounds(510, 730, 90, 30);

        jTextFieldLastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldLastName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldLastNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldLastNameFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldLastName);
        jTextFieldLastName.setBounds(810, 110, 220, 50);

        jTextFieldAccsoftID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldAccsoftID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldAccsoftID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldAccsoftIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldAccsoftIDFocusLost(evt);
            }
        });
        jTextFieldAccsoftID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldAccsoftIDKeyTyped(evt);
            }
        });
        jPanel2.add(jTextFieldAccsoftID);
        jTextFieldAccsoftID.setBounds(650, 270, 380, 40);

        jTextFieldPhoneNo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextFieldPhoneNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldPhoneNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldPhoneNoFocusLost(evt);
            }
        });
        jTextFieldPhoneNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneNoKeyTyped(evt);
            }
        });
        jPanel2.add(jTextFieldPhoneNo);
        jTextFieldPhoneNo.setBounds(650, 470, 250, 50);

        jComboBoxInstitution.setBackground(new java.awt.Color(255, 153, 0));
        jComboBoxInstitution.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxInstitution.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jai Narain College & Research Center", "L N Nursing College", "L N Nursing School", "Lakshmi Narain College of Pharmacy", "Lakshmi Narain College of Technology", "Lakshmi Narain College of Technology - MBA", "Lakshmi Narain College of Technology - MCA", "Lakshmi Narain College of Technology Excellence", "Lakshmi Narain College of Technology and Science" }));
        jComboBoxInstitution.setBorder(null);
        jPanel2.add(jComboBoxInstitution);
        jComboBoxInstitution.setBounds(650, 330, 380, 40);

        jBtnGroupGender.add(jRadioButtonMale);
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRadioButtonMaleFocusGained(evt);
            }
        });
        jPanel2.add(jRadioButtonMale);
        jRadioButtonMale.setBounds(650, 570, 60, 30);

        jBtnGroupGender.add(jRadioButtonFemale);
        jRadioButtonFemale.setText("Female");
        jRadioButtonFemale.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jRadioButtonFemale.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRadioButtonFemaleFocusGained(evt);
            }
        });
        jPanel2.add(jRadioButtonFemale);
        jRadioButtonFemale.setBounds(730, 570, 80, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryapp/AppImages/name_frame.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(590, 110, 420, 70);

        jLabelAccsoftID.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabelAccsoftID.setForeground(new java.awt.Color(122, 122, 122));
        jLabelAccsoftID.setText("Accsoft ID:");
        jPanel2.add(jLabelAccsoftID);
        jLabelAccsoftID.setBounds(520, 280, 110, 30);

        jLabelCollege.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabelCollege.setForeground(new java.awt.Color(122, 122, 122));
        jLabelCollege.setText("COLLEGE:");
        jPanel2.add(jLabelCollege);
        jLabelCollege.setBounds(520, 340, 110, 30);

        jLabelSemester.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabelSemester.setForeground(new java.awt.Color(122, 122, 122));
        jLabelSemester.setText("SEMESTER:");
        jPanel2.add(jLabelSemester);
        jLabelSemester.setBounds(520, 410, 120, 30);

        jLabelSection.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabelSection.setForeground(new java.awt.Color(122, 122, 122));
        jLabelSection.setText("SECTION:");
        jPanel2.add(jLabelSection);
        jLabelSection.setBounds(840, 410, 100, 30);

        jLabelEmailEx.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelEmailEx.setForeground(new java.awt.Color(203, 209, 216));
        jLabelEmailEx.setText("example@email.com");
        jPanel2.add(jLabelEmailEx);
        jLabelEmailEx.setBounds(650, 200, 260, 40);

        jLabelEmail.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(122, 122, 122));
        jLabelEmail.setText("EMAIL:");
        jPanel2.add(jLabelEmail);
        jLabelEmail.setBounds(520, 210, 80, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryapp/AppImages/phone_number.jpg"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(650, 470, 250, 70);

        jLabelGenderWarning.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelGenderWarning.setForeground(new java.awt.Color(255, 0, 0));
        jLabelGenderWarning.setText("*");
        jPanel2.add(jLabelGenderWarning);
        jLabelGenderWarning.setBounds(810, 570, 20, 30);

        jLabelPhone.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabelPhone.setForeground(new java.awt.Color(122, 122, 122));
        jLabelPhone.setText("PHONE:");
        jPanel2.add(jLabelPhone);
        jLabelPhone.setBounds(520, 480, 90, 40);

        jLabelGender.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabelGender.setForeground(new java.awt.Color(122, 122, 122));
        jLabelGender.setText("GENDER:");
        jPanel2.add(jLabelGender);
        jLabelGender.setBounds(520, 570, 100, 30);

        jLabelBranch.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabelBranch.setForeground(new java.awt.Color(122, 122, 122));
        jLabelBranch.setText("BRANCH:");
        jPanel2.add(jLabelBranch);
        jLabelBranch.setBounds(520, 620, 100, 50);

        jComboBoxBranch.setBackground(new java.awt.Color(255, 153, 0));
        jComboBoxBranch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxBranch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Architecture Engineering", "Automobile Engineering", "Civil Engineering", "Chemical Engineering", "Computer Science & Engineering", "Electronics & Communication Engineering", "Electrical Engineering", "Electronics & Instrumentation Engineering", "Food Technology Engineering", "Information Technology", "Industrial Production Engineering", "Mechanical Engineering" }));
        jPanel2.add(jComboBoxBranch);
        jComboBoxBranch.setBounds(650, 630, 380, 30);

        jComboBoxSection.setBackground(new java.awt.Color(255, 153, 0));
        jComboBoxSection.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxSection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C" }));
        jComboBoxSection.setBorder(null);
        jPanel2.add(jComboBoxSection);
        jComboBoxSection.setBounds(950, 410, 80, 30);

        jComboBoxSemester.setBackground(new java.awt.Color(255, 153, 0));
        jComboBoxSemester.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBoxSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        jComboBoxSemester.setBorder(null);
        jPanel2.add(jComboBoxSemester);
        jComboBoxSemester.setBounds(650, 410, 80, 30);

        jLabelHaveAccount.setFont(new java.awt.Font("Arial", 3, 15)); // NOI18N
        jLabelHaveAccount.setForeground(new java.awt.Color(122, 122, 122));
        jLabelHaveAccount.setText("Sign In Instead ?");
        jPanel2.add(jLabelHaveAccount);
        jLabelHaveAccount.setBounds(820, 730, 120, 30);

        jLabelName.setFont(new java.awt.Font("Arial", 3, 20)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(122, 122, 122));
        jLabelName.setText("NAME:");
        jPanel2.add(jLabelName);
        jLabelName.setBounds(520, 120, 70, 24);

        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldEmailFocusLost(evt);
            }
        });
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(649, 202, 380, 40);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryapp/AppImages/white_frame.jpg"))); // NOI18N
        jPanel2.add(jLabel26);
        jLabel26.setBounds(500, 100, 560, 670);

        jLabelCollegeLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/libraryapp/AppImages/lnct_logo.png"))); // NOI18N
        jPanel2.add(jLabelCollegeLogo);
        jLabelCollegeLogo.setBounds(70, 270, 220, 210);

        jLabelRegistration.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 60)); // NOI18N
        jLabelRegistration.setForeground(new java.awt.Color(255, 0, 0));
        jLabelRegistration.setText("Registration");
        jPanel2.add(jLabelRegistration);
        jLabelRegistration.setBounds(670, 20, 310, 80);
        jPanel2.add(jTextFieldHidden);
        jTextFieldHidden.setBounds(1079, 0, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static final String VOICENAME = "kevin16";

    private void jTextFieldEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusGained
        jLabelEmailEx.setVisible(false);

    }//GEN-LAST:event_jTextFieldEmailFocusGained

    private void jTextFieldEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldEmailFocusLost
        if (jTextFieldEmail.getText().trim().isEmpty()) {
            jLabelEmailEx.setVisible(true);
        }
    }//GEN-LAST:event_jTextFieldEmailFocusLost

    private void jTextFieldFirstNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameFocusLost
        if (jTextFieldFirstName.getText().trim().isEmpty()) {
            jTextFieldFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
    }//GEN-LAST:event_jTextFieldFirstNameFocusLost

    private void jTextFieldFirstNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameFocusGained
        jTextFieldFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jTextFieldFirstNameFocusGained

    private void jTextFieldLastNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLastNameFocusGained
        jTextFieldLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jTextFieldLastNameFocusGained

    private void jTextFieldLastNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldLastNameFocusLost
        if (jTextFieldLastName.getText().trim().isEmpty()) {
            jTextFieldLastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
    }//GEN-LAST:event_jTextFieldLastNameFocusLost

    private void jTextFieldAccsoftIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccsoftIDFocusGained
        jTextFieldAccsoftID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jTextFieldAccsoftIDFocusGained

    private void jTextFieldAccsoftIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldAccsoftIDFocusLost
        if (jTextFieldAccsoftID.getText().trim().isEmpty()) {
            jTextFieldAccsoftID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
    }//GEN-LAST:event_jTextFieldAccsoftIDFocusLost

    private void jTextFieldPhoneNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNoFocusGained
        jTextFieldPhoneNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_jTextFieldPhoneNoFocusGained

    private void jTextFieldPhoneNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNoFocusLost
        if (jTextFieldPhoneNo.getText().trim().isEmpty()) {
            jTextFieldPhoneNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        }
    }//GEN-LAST:event_jTextFieldPhoneNoFocusLost

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        if (!jRadioButtonMale.isSelected() && !jRadioButtonFemale.isSelected()) {
            jLabelGenderWarning.setVisible(true);
            if (jTextFieldPhoneNo.getText().trim().isEmpty() || jTextFieldAccsoftID.getText().trim().isEmpty() || jTextFieldLastName.getText().trim().isEmpty() || jTextFieldFirstName.getText().trim().isEmpty()) {
                jTextFieldPhoneNo.requestFocus();
                jTextFieldAccsoftID.requestFocus();
                jTextFieldLastName.requestFocus();
                jTextFieldFirstName.requestFocus();
                jTextFieldHidden.requestFocus();
                String str;
                str = "Empty Fields !!";
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, str, "ACCESS DENIED !!", JOptionPane.ERROR_MESSAGE);
            } else {
                String str;
                str = "Empty Fields !!";
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, str, "ACCESS DENIED !!", JOptionPane.ERROR_MESSAGE);
            }
        } else if (jTextFieldPhoneNo.getText().trim().isEmpty() || jTextFieldAccsoftID.getText().trim().isEmpty() || jTextFieldLastName.getText().trim().isEmpty() || jTextFieldFirstName.getText().trim().isEmpty()) {
            jTextFieldPhoneNo.requestFocus();
            jTextFieldAccsoftID.requestFocus();
            jTextFieldLastName.requestFocus();
            jTextFieldFirstName.requestFocus();
            jTextFieldHidden.requestFocus();
            String str;
            str = "Empty Fields !!";
            JOptionPane.showMessageDialog(null, str, "ACCESS DENIED !!", JOptionPane.ERROR_MESSAGE);
        }
        else {
            String fName = jTextFieldFirstName.getText().trim();
            String lName = jTextFieldLastName.getText().trim();
            String email = jTextFieldEmail.getText().trim();
            String id = jTextFieldAccsoftID.getText().trim();
            String cllg = jComboBoxInstitution.getItemAt(jComboBoxInstitution.getSelectedIndex());
            int sem = Integer.parseInt(jComboBoxSemester.getItemAt(jComboBoxSemester.getSelectedIndex()));
            String sec = jComboBoxSection.getItemAt(jComboBoxSection.getSelectedIndex());
            long pno = Long.parseLong(jTextFieldPhoneNo.getText().trim());
            String branch = jComboBoxBranch.getItemAt(jComboBoxBranch.getSelectedIndex());
            String gen;
            if (jRadioButtonMale.isSelected()) {
                gen = "Male";
            } else {
                gen = "Female";
            }
            try {
                StudentPojo studentDetails = new StudentPojo(fName, lName, email, id, cllg, sem, sec, pno, gen, branch);
                if (addStudent(studentDetails)) {
//                    Voice voice;
//                    VoiceManager vm = VoiceManager.getInstance();
//                    voice = vm.getVoice(VOICENAME);
//                    voice.allocate();
//                    voice.speak("Account Successfully Created");
                    JOptionPane.showMessageDialog(null, "Account Successfully Created", "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    jTextFieldFirstName.setText("");
                    jTextFieldLastName.setText("");
                    jTextFieldEmail.setText("");
                    jTextFieldAccsoftID.setText("");
                    jTextFieldPhoneNo.setText("");
                    jTextFieldHidden.requestFocus();
                }
            } catch (SQLException ex) {
                if (ex.getErrorCode() == 1) {
                    JOptionPane.showMessageDialog(null, "Accsoft ID or Mobile Number already exists !!");
                }
                else {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(null, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jRadioButtonMaleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButtonMaleFocusGained
        jLabelGenderWarning.setVisible(false);
    }//GEN-LAST:event_jRadioButtonMaleFocusGained

    private void jRadioButtonFemaleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButtonFemaleFocusGained
        jLabelGenderWarning.setVisible(false);
    }//GEN-LAST:event_jRadioButtonFemaleFocusGained

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        LoginPage loginobj = new LoginPage();
        loginobj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        jTextFieldFirstName.setText("");
        jTextFieldFirstName.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        jTextFieldLastName.setText("");
        jTextFieldLastName.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        jTextFieldEmail.setText("");
        jTextFieldEmail.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        jTextFieldAccsoftID.setText("");
        jTextFieldAccsoftID.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        jTextFieldPhoneNo.setText("");
        jTextFieldPhoneNo.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK));
        jTextFieldFirstName.requestFocus();
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jTextFieldAccsoftIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldAccsoftIDKeyTyped
        char c = evt.getKeyChar();
        String id;
        id = jTextFieldAccsoftID.getText().trim();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE) || id.length() > 10) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldAccsoftIDKeyTyped

    private void jTextFieldPhoneNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNoKeyTyped
        char c;
        c = evt.getKeyChar();
        String pno;
        pno = jTextFieldPhoneNo.getText().trim();
        if (!(Character.isDigit(c) || c == KeyEvent.VK_BACKSPACE || c == KeyEvent.VK_DELETE) || pno.length() > 9) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jTextFieldPhoneNoKeyTyped

    private void jTextFieldFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFirstNameKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            jTextFieldLastName.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldFirstNameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegistrationPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jBtnGroupGender;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JComboBox<String> jComboBoxBranch;
    private javax.swing.JComboBox<String> jComboBoxInstitution;
    private javax.swing.JComboBox<String> jComboBoxSection;
    private javax.swing.JComboBox<String> jComboBoxSemester;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAccsoftID;
    private javax.swing.JLabel jLabelBranch;
    private javax.swing.JLabel jLabelCollege;
    private javax.swing.JLabel jLabelCollegeLogo;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEmailEx;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelGenderWarning;
    private javax.swing.JLabel jLabelHaveAccount;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhone;
    private javax.swing.JLabel jLabelRegistration;
    private javax.swing.JLabel jLabelSection;
    private javax.swing.JLabel jLabelSemester;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JTextField jTextFieldAccsoftID;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName;
    private javax.swing.JTextField jTextFieldHidden;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPhoneNo;
    // End of variables declaration//GEN-END:variables
}
